dj4e/dj4e-samples-main/chat/urls.py
import os
from django.urls import path, re_path
from django.views.static import serve
from . import views
from django.views.generic import TemplateView

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

app_name='chat'
urlpatterns = [
    path('', views.TalkMain.as_view(), name='talk'),
    path('messages', views.TalkMessages.as_view(), name='messages'),

    # Serve up a local static folder to serve spinner.gif
    re_path(r'^static/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'static'), 'show_indexes': True},
        name='static'
    )
]

dj4e/dj4e-samples-main/dj4e-samples/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('home.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

    # Sample applications
    path('hello/', include('hello.urls')),
    path('users/', include('users.urls')),
    path('tracks/', include('tracks.urls')),
    path('views/', include('views.urls')),
    path('route/', include('route.urls', namespace='nsroute')),
    path('tmpl/', include('tmpl.urls')),
    path('gview/', include('gview.urls')),
    path('session/', include('session.urls')),
    path('authz/', include('authz.urls')),
    path('getpost/', include('getpost.urls')),
    path('form/', include('form.urls')),
    path('crispy/', include('crispy.urls')),
    path('myarts/', include('myarts.urls')),
    path('menu/', include('menu.urls')),
    path('forums/', include('forums.urls')),
    path('pics/', include('pics.urls')),
    path('favs/', include('favs.urls')),
    path('favsql/', include('favsql.urls')),
    path('rest/', include('rest.urls')),
    path('autos/', include('autos.urls')),
    path('usermodel/', include('usermodel.urls')),
    path('fetch/', include('fetch.urls')),
    path('chat/', include('chat.urls')),
    path('util/', include('util.urls')),
    path('well/', include('well.urls')),
    path('tagme/', include('tagme.urls')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/4.2/ref/urls/#include

dj4e/dj4e-samples-main/fetch/urls.py
import os
from django.urls import path, re_path
from django.views.static import serve
from . import views
from django.views.generic import TemplateView

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

app_name='fetch'
urlpatterns = [
    path('', views.HomeView.as_view(), name='main'),
    path('syntax', TemplateView.as_view(template_name='fetch/syntax.html'), 
        name='syntax'),
    path('async', TemplateView.as_view(template_name='fetch/async.html'), 
        name='async'),
    path('promise', TemplateView.as_view(template_name='fetch/promise.html'), 
        name='promise'),
    path('jsonfun', views.jsonfun, name='jsonfun'),

]

dj4e/dj4e-samples-main/fetch/models.py
from django.db import models

# Create your models here.

dj4e/dj4e-samples-main/fetch/views.py
from django.shortcuts import render, redirect, reverse
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.http import JsonResponse, HttpResponse
from datetime import datetime, timedelta
from django.utils.html import escape
import time

class HomeView(View) :
    def get(self, request):
        return render(request, 'fetch/main.html')

def jsonfun(request):
    time.sleep(2)
    stuff = {
        'first': 'first thing',
        'second': 'second thing'
    }
    return JsonResponse(stuff)

# References

# https://simpleisbetterthancomplex.com/tutorial/2016/07/27/how-to-return-json-encoded-response.html

dj4e/dj4e-samples-main/fetch/templates/fetch/async.html
{% extends 'base_bootstrap.html' %}
{% block content %}
<p>Lets get some JSON using 
<a href="https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch" target="_blank">fetch</a> and
async / await.  Turn on your developer console and press the buttons below:</p>
<p>
<button onclick="loadUrl('hddp://x/broken', 'urlsyntax');return false;">URL Syntax Fail</button>
</p>
<p id="urlsyntax">New text will not go here</span></p>
<p>
<button onclick="loadUrl('/broken', 'requestfail');return false;">Request 404</button>
</p>
<p id="requestfail">New text will not go here</span></p>
<p>
<button onclick="loadUrl('{% url 'fetch:main' %}', 'jsonfail');return false;">JSON Parse Fail</button>
</p>
<p id="jsonfail">New text will not go here</span></p>
<p>
<button onclick="loadUrl('{% url 'fetch:jsonfun' %}', 'working');return false;">Retrieve Data</button> 
</p>
<p id="working">New text will go here!!!!</span></p>
<script type="text/javascript">

async function loadUrl(url, id) {
    console.log("Loading", url);
    document.getElementById(id).style.color = 'orange';
    document.getElementById(id).innerHTML = 'Loading...';

    // Either start the request or have a broken request
    const request = fetch(url).catch((error) => {
        const txt = 'Could not start fetch\nURL:'+url+'\n'+error;
        return txt;
    });

    console.log('request', request);
    const response = await request;
    console.log('response', response);

    // A failure to start the fetch returns an error string
    if ( typeof response == 'string' ) {
        document.getElementById(id).innerHTML = response;
        document.getElementById(id).style.color = 'red';
        return response;
    }

    // Request worked but we got a non-200 response
    if ( ! response.ok ) {
        const txt = 'Fetch Failed\nURL:'+url+'\nStatus:'+response.status+' '+response.statusText;
        console.log(txt);
        document.getElementById(id).innerHTML = txt;
        document.getElementById(id).style.color = 'red';
        return txt;
    }

    // Got a 200, parse the response as JSON
    const data = await response.json().catch((error) => {return error.toString()} );

    console.log('JSON data', data);
    if ( typeof data == 'object' ) {
        document.getElementById(id).style.color = 'green';
        document.getElementById(id).innerHTML = 'Async: ' + data.first;
    } else {
        document.getElementById(id).style.color = 'red';
        document.getElementById(id).innerHTML = data;
    }
    return data;
}

</script>
{% endblock %}
</body>

dj4e/dj4e-samples-main/fetch/templates/fetch/main.html
{% extends 'base_bootstrap.html' %}
{% block content %}
<p>JSON / AJAX / FETCH Examples</p>
<p>
<a href="{% url 'fetch:syntax' %}" target="_blank">JavaScript Object Syntax</a> |
<a href="{% url 'fetch:jsonfun' %}" target="_blank">Load JSON in Browser</a>
</p>
<p>
<a href="{% url 'fetch:promise' %}" target="_blank">Fetch JSON with Promises</a>  |
<a href="{% url 'fetch:async' %}" target="_blank">Fetch JSON with Async / Await</a>
</p>
{% endblock %}
</body>

dj4e/dj4e-samples-main/fetch/templates/fetch/promise.html
{% extends 'base_bootstrap.html' %}
{% block content %}
<p>Lets get some JSON using 
<a href="https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch" target="_blank">fetch</a>
and promise syntax.  Turn on your developer console and press the buttons below:</p>
<p>
<button onclick="loadUrl('hddp://x/broken', 'urlsyntax');return false;">URL Syntax Fail</button>
</p>
<p id="urlsyntax">New text will not go here</span></p>
<p>
<button onclick="loadUrl('/broken', 'requestfail');return false;">Request 404</button>
</p>
<p id="requestfail">New text will not go here</span></p>
<p>
<button onclick="loadUrl('{% url 'fetch:main' %}', 'jsonfail');return false;">JSON Parse Fail</button>
</p>
<p id="jsonfail">New text will not go here</span></p>
<p>
<button onclick="loadUrl('{% url 'fetch:jsonfun' %}', 'working');return false;">Retrieve Data</button>
</p>
<p id="working">New text will go here!!!!</span></p>
<script type="text/javascript">

function loadUrl(url, id) {
    console.log("Loading", url);
    document.getElementById(id).style.color = 'orange';
    document.getElementById(id).innerHTML = 'Loading...';

    fetch(url, {cache: "no-store"})
      .then((response) => response.json())
      .then((data) => {
        console.log('JSON data', data);
        document.getElementById(id).style.color = 'green';
        document.getElementById(id).innerHTML = 'Promise: ' + data.first;
      })
      .catch((error) => {
        document.getElementById(id).style.color = 'red';
        document.getElementById(id).innerHTML = error;
      });
}

</script>
{% endblock %}
</body>

dj4e/dj4e-samples-main/fetch/templates/fetch/syntax.html
<html><head/><body>
<p>JavaScript Object Constants</p>
<script type="text/javascript">
who = {
    "name": "Chuck",
    "age": 29, 
    "college": true,
    "offices" : [ "3350DMC", "3437NQ" ],
    "skills" : { "fortran": 10, "C": 10, 
        "C++": 5, "python" : 7 }
};
console.log(who);
</script>
<p>Check out the console.log to see the cool object</p>
</body>