dj4e/dj4e-samples-main/chat/urls.py
import os
from django.urls import path, re_path
from django.views.static import serve
from . import views
from django.views.generic import TemplateView

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

app_name='chat'
urlpatterns = [
    path('', views.TalkMain.as_view(), name='talk'),
    path('messages', views.TalkMessages.as_view(), name='messages'),

    # Serve up a local static folder to serve spinner.gif
    re_path(r'^static/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'static'), 'show_indexes': True},
        name='static'
    )
]

dj4e/dj4e-samples-main/dj4e-samples/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('home.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

    # Sample applications
    path('hello/', include('hello.urls')),
    path('users/', include('users.urls')),
    path('tracks/', include('tracks.urls')),
    path('views/', include('views.urls')),
    path('route/', include('route.urls', namespace='nsroute')),
    path('tmpl/', include('tmpl.urls')),
    path('gview/', include('gview.urls')),
    path('session/', include('session.urls')),
    path('authz/', include('authz.urls')),
    path('getpost/', include('getpost.urls')),
    path('form/', include('form.urls')),
    path('crispy/', include('crispy.urls')),
    path('myarts/', include('myarts.urls')),
    path('menu/', include('menu.urls')),
    path('forums/', include('forums.urls')),
    path('pics/', include('pics.urls')),
    path('favs/', include('favs.urls')),
    path('favsql/', include('favsql.urls')),
    path('rest/', include('rest.urls')),
    path('autos/', include('autos.urls')),
    path('usermodel/', include('usermodel.urls')),
    path('fetch/', include('fetch.urls')),
    path('chat/', include('chat.urls')),
    path('util/', include('util.urls')),
    path('well/', include('well.urls')),
    path('tagme/', include('tagme.urls')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/4.2/ref/urls/#include

dj4e/dj4e-samples-main/well/urls.py
from django.urls import path, reverse_lazy
from . import views
from . import models
from myarts.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView

app_name='well'
urlpatterns = [
    path('', views.PostListView.as_view(), name='all'),

    path('post/<int:pk>', 
        OwnerDetailView.as_view(
            model = models.Post,
            template_name = app_name+"/detail.html"), 
        name='post_detail'),

    path('post/create', 
        OwnerCreateView.as_view(
            success_url=reverse_lazy(app_name+':all'),
            model = models.Post,
            template_name = app_name+"/form.html",
            fields = ['title', 'text']
         ), name='post_create'),

    path('post/<int:pk>/update', 
        OwnerUpdateView.as_view(
            success_url=reverse_lazy(app_name+':all'),
            model = models.Post,
            fields = ['title', 'text'],
            template_name = app_name+"/form.html"
        ), name='post_update'),

    path('post/<int:pk>/delete', 
        OwnerDeleteView.as_view(
            success_url=reverse_lazy(app_name+':all'),
            model = models.Post,
            template_name = app_name+"/delete.html"
        ), name='post_delete'),

]

dj4e/dj4e-samples-main/well/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User
from django.conf import settings

class Post(models.Model) :
    title = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    text = models.TextField()

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
            related_name='post_owner')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        return self.title

dj4e/dj4e-samples-main/well/views.py
from django.shortcuts import render
from well.models import Post
from django.views import View
from django.contrib.humanize.templatetags.humanize import naturaltime

from django.db.models import Q

class PostListView(View):
    template_name = "well/list.html"

    def get(self, request) :
        strval =  request.GET.get("search", False)
        if strval :
            # Simple title-only search
            # objects = Post.objects.filter(title__contains=strval).select_related().distinct().order_by('-updated_at')[:10]

            # Multi-field search
            # __icontains for case-insensitive search
            query = Q(title__icontains=strval) 
            query.add(Q(text__icontains=strval), Q.OR)
            post_list = Post.objects.filter(query).select_related().distinct().order_by('-updated_at')[:10]
        else :
            post_list = Post.objects.all().order_by('-updated_at')[:10]

        # Augment the post_list
        for obj in post_list:
            obj.natural_updated = naturaltime(obj.updated_at)

        ctx = {'post_list' : post_list, 'search': strval}
        return render(request, self.template_name, ctx)

# References

# https://docs.djangoproject.com/en/4.2/topics/db/queries/#one-to-many-relationships

# Note that the select_related() QuerySet method recursively prepopulates the
# cache of all one-to-many relationships ahead of time.

# sql “LIKE” equivalent in django query
# https://stackoverflow.com/questions/18140838/sql-like-equivalent-in-django-query

# How do I do an OR filter in a Django query?
# https://stackoverflow.com/questions/739776/how-do-i-do-an-or-filter-in-a-django-query

# https://stackoverflow.com/questions/1074212/how-can-i-see-the-raw-sql-queries-django-is-running

dj4e/dj4e-samples-main/well/templates/well/delete.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Delete Post</h1>

<p>Are you sure you want to delete: {{ post }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" value="Cancel" onclick="window.location.href='{% url 'well:all' %}';return false;">
</form>
{% endblock %}

dj4e/dj4e-samples-main/well/templates/well/detail.html
{% extends "base_bootstrap.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/4.2/ref/contrib/humanize -->
{% block content %}
<span style="float: right;">
({{ post.updated_at|naturaltime }})
{% if post.owner == user %}
<a href="{% url 'well:post_update' post.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'well:post_delete' post.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<h1>{{ post.title }}</h1>
<p>
{{ post.text }}
</p>
<p>
</p>
<p>
<a href="{% url 'well:all' %}">All posts</a>
</p>
{% endblock %}

dj4e/dj4e-samples-main/well/templates/well/form.html
{% extends "base_bootstrap.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'well:all' %}';return false;">
  </form>
</p>
{% endblock %}

dj4e/dj4e-samples-main/well/templates/well/list.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Our Blog</h1>
<div style="float:right">
<!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
<form>
  <input type="text" placeholder="Search.." name="search"
  {% if search %} value="{{ search }}" {% endif %}
  >
  <button type="submit"><i class="fa fa-search"></i></button>
<a href="{% url 'well:all' %}"><i class="fa fa-undo"></i></a>
</form>
</div>
<p>
{% if post_list %}
<ul>
  {% for post in post_list %}
    <li>
        <a href="{% url 'well:post_detail'  post.id %}">{{ post.title }}</a>
        {% if post.owner_id == user.id %}
        (<a href="{% url 'well:post_update' post.id %}">Edit</a> |
        <a href="{% url 'well:post_delete' post.id %}">Delete</a>)
        <br/>
        {% endif %}
        <div style="left:10px">
            {% if post.text|length < 100 %}
                {{ post.text }}
            {% else %}
                {{ post.text|slice:"0:99" }}
                <a href="{% url 'well:post_detail'  post.id %}">...</a>
            {% endif %}
        </div>
        <small>
        {% if post.owner.username %}
            posted by {{ post.owner.username }}
        {% endif %}
        {{ post.natural_updated }}
        </small>
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no posts in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'well:post_create' %}">Add a Post</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'well:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'well:all' %}">Login</a>
{% endif %}
</p>
{% endblock %}