dj4e/dj4e-samples-main/chat/urls.py
import os
from django.urls import path, re_path
from django.views.static import serve
from . import views
from django.views.generic import TemplateView

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

app_name='chat'
urlpatterns = [
    path('', views.TalkMain.as_view(), name='talk'),
    path('messages', views.TalkMessages.as_view(), name='messages'),

    # Serve up a local static folder to serve spinner.gif
    re_path(r'^static/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'static'), 'show_indexes': True},
        name='static'
    )
]

dj4e/dj4e-samples-main/dj4e-samples/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('home.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

    # Sample applications
    path('hello/', include('hello.urls')),
    path('users/', include('users.urls')),
    path('tracks/', include('tracks.urls')),
    path('views/', include('views.urls')),
    path('route/', include('route.urls', namespace='nsroute')),
    path('tmpl/', include('tmpl.urls')),
    path('gview/', include('gview.urls')),
    path('session/', include('session.urls')),
    path('authz/', include('authz.urls')),
    path('getpost/', include('getpost.urls')),
    path('form/', include('form.urls')),
    path('crispy/', include('crispy.urls')),
    path('myarts/', include('myarts.urls')),
    path('menu/', include('menu.urls')),
    path('forums/', include('forums.urls')),
    path('pics/', include('pics.urls')),
    path('favs/', include('favs.urls')),
    path('favsql/', include('favsql.urls')),
    path('rest/', include('rest.urls')),
    path('autos/', include('autos.urls')),
    path('usermodel/', include('usermodel.urls')),
    path('fetch/', include('fetch.urls')),
    path('chat/', include('chat.urls')),
    path('util/', include('util.urls')),
    path('well/', include('well.urls')),
    path('tagme/', include('tagme.urls')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/4.2/ref/urls/#include

dj4e/dj4e-samples-main/gview/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

# https://docs.djangoproject.com/en/4.2/topics/http/urls/

# To make {% url 'gview:cats' %} work in templates
# Also, add namespace in project urls.py

app_name = 'gview'

# Note use of plural for list view and singular for detail view
urlpatterns = [
    path('', TemplateView.as_view(template_name='gview/main.html')),
    path('cats', views.CatListView.as_view(), name='cats'),
    path('cat/<int:pk_from_url>', views.CatDetailView.as_view(), name='cat'),
    path('dogs', views.DogListView.as_view(), name='dogs'),
    path('dog/<int:pk>', views.DogDetailView.as_view(), name='dog'),
    path('horses', views.HorseListView.as_view(), name='horses'),
    path('horse/<int:pk>', views.HorseDetailView.as_view(), name='horse'),
    path('cars', views.CarListView.as_view(), name='cars'),
    path('car/<int:pk>', views.CarDetailView.as_view(), name='car'),
    path('wacky', views.WackyEquinesView.as_view(), name='whatever'),
]

dj4e/dj4e-samples-main/gview/models.py
from django.db import models

# Create your models here.

from django.db import models

class Cat(models.Model):
    name = models.CharField(max_length=128)

class Dog(models.Model):
    name = models.CharField(max_length=128)

class Horse(models.Model):
    name = models.CharField(max_length=128)

class Car(models.Model):
    name = models.CharField(max_length=128)

dj4e/dj4e-samples-main/gview/views.py
from gview.models import Cat, Dog, Horse, Car

from django.views import View
from django.shortcuts import render

# Create your views here.

class CatListView(View):
    def get(self, request) :
        stuff = Cat.objects.all()
        cntx = { 'cat_list': stuff }
        return render(request, 'gview/cat_list.html', cntx)

class CatDetailView(View):
    def get(self, request, pk_from_url) :
        obj = Cat.objects.get(pk=pk_from_url)
        cntx = { 'cat': obj }
        return render(request, 'gview/cat_detail.html', cntx)

# Lets apply the "DRY" pattern - "Don't Repeat Yourself"
class DogListView(View):
    model = Dog
    def get(self, request) :
        modelname = self.model._meta.verbose_name.title().lower()
        stuff = self.model.objects.all()
        cntx = { modelname+'_list': stuff }
        return render(request, 'gview/'+modelname+'_list.html', cntx)

class DogDetailView(View):
    model = Dog
    def get(self, request, pk) :
        modelname = self.model._meta.verbose_name.title().lower()
        obj = self.model.objects.get(pk=pk)
        cntx = { modelname : obj }
        return render(request, 'gview/'+modelname+'_detail.html', cntx)

# Lets save time and use the built-in generics
# https://docs.djangoproject.com/en/4.2/topics/class-based-views/generic-display/
from django.views import generic

class HorseListView(generic.ListView):
    model = Horse

class HorseDetailView(generic.DetailView):
    model = Horse

# Lets review how inheritance works to avoid repeating ourselves
# It is all about convention
class DJ4EListView(View):
    def get(self, request) :
        modelname = self.model._meta.verbose_name.title().lower()
        stuff = self.model.objects.all()
        cntx = { modelname+'_list': stuff }
        return render(request, 'gview/'+modelname+'_list.html', cntx)

class DJ4EDetailView(View):
    def get(self, request, pk) :
        modelname = self.model._meta.verbose_name.title().lower()
        obj = self.model.objects.get(pk=pk)
        cntx = { modelname : obj }
        return render(request, 'gview/'+modelname+'_detail.html', cntx)

# Lets reuse those "generic" classes
class CarListView(DJ4EListView):
    model = Car

class CarDetailView(DJ4EDetailView):
    model = Car

# Lets explore how (badly) we can override some of what goes on...
class WackyEquinesView(generic.ListView):
    model = Car
    template_name = 'gview/wacky.html'  # Convention: gview/car_list.html

    def get_queryset(self, **kwargs):
        crazy = Horse.objects.all()    # Convention: Car
        print('CRAZY')
        return crazy

    # Add something to the context
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['crazy_thing'] = 'CRAZY THING'
        return context

# There is much more to learn
# https://docs.djangoproject.com/en/4.2/ref/class-based-views/generic-display/#django.views.generic.detail.DetailView
# https://docs.djangoproject.com/en/4.2/ref/class-based-views/generic-display/#django.views.generic.detail.ListView

dj4e/dj4e-samples-main/gview/templates/gview/car_detail.html
<h1>Car {{ car.name }}</h1>
<p>
<a href="{% url 'gview:cars' %}">Go back to list</a>
</p>
<p>
<a href="https://www.sakaiger.com/#sakaicar" target="_blank">
<img src="https://www.sakaiger.com/images/2018-10-SakaiCar-Gingerman-Neon-Square.jpeg"
     width="160"
    alt="A picture of a White and Blue Dodge Neon with ears (a.k.a SakaiCar)">
</a>
</p>

dj4e/dj4e-samples-main/gview/templates/gview/car_list.html
<h1>Car List</h1>
<p>
{% if car_list %}
<ul>
  {% for car in car_list %}
    <li>
        <a href="{% url 'gview:car' car.id %}">{{ car.name }}</a>
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no cars in the database.</p>
{% endif %}
</p>

dj4e/dj4e-samples-main/gview/templates/gview/cat_detail.html
<h1>Cat {{ cat.name }}</h1>
<p>
<a href="{% url 'gview:cats' %}">Go back to list</a>
</p>
<p>
<img src="https://loremflickr.com/160/120/cat" 
    alt="A random picture of a cat">
</p>

dj4e/dj4e-samples-main/gview/templates/gview/cat_list.html
<h1>Cat List</h1>
<p>
{% if cat_list %}
<ul>
  {% for cat in cat_list %}
    <li>
      <a href="{% url 'gview:cat' cat.id %}">{{ cat.name }}</a>
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no cats in the database.</p>
{% endif %}
</p>

dj4e/dj4e-samples-main/gview/templates/gview/dog_detail.html
<h1>Dog {{ dog.name }}</h1>
<p>
<a href="{% url 'gview:dogs' %}">Go back to list</a>
</p>
<p>
<img src="https://loremflickr.com/160/120/dog" 
    alt="A random picture of a dog">
</p>

dj4e/dj4e-samples-main/gview/templates/gview/dog_list.html
<h1>Dog List</h1>
<p>
{% if dog_list %}
<ul>
  {% for dog in dog_list %}
    <li>
      <a href="{% url 'gview:dog' dog.id %}">{{ dog.name }}</a>
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no dogs in the database.</p>
{% endif %}
</p>

dj4e/dj4e-samples-main/gview/templates/gview/horse_detail.html
<h1>Horse {{ horse.name }}</h1>
<p>
<img src="https://loremflickr.com/160/120/horse" 
    alt="A random picture of a horse">
</p>
<p>
<a href="{% url 'gview:horses' %}">Go back to list</a>
</p>

dj4e/dj4e-samples-main/gview/templates/gview/horse_list.html
<h1>Horse List</h1>
<p>
{% if horse_list %}
<ul>
  {% for horse in horse_list %}
    <li>
      <a href="{% url 'gview:horse' horse.id %}">{{ horse.name }}</a>
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no horses in the database.</p>
{% endif %}
</p>

dj4e/dj4e-samples-main/gview/templates/gview/main.html
<html><body><p>This is the generic main.html sample</p>
<p>
This page is coming from a file in gview/templates/gview/main.html
</p>
<ul>
    <li><a href="{% url 'gview:cats' %}">A list of cats</a></li>
    <li><a href="{% url 'gview:dogs' %}">A list of dogs</a></li>
    <li><a href="{% url 'gview:horses' %}">A list of horses</a></li>
    <li><a href="{% url 'gview:cars' %}">A list of cars</a></li>
    <li><a href="{% url 'gview:whatever' %}">A list that uses an unconventional view</a></li>
</ul>
</p>
<p>
Data loading instructions:
<pre>
In linux, Mac terminal, or PythonAnywhere shell run this in the manage.py folder:

python3 manage.py runscript gview_load
</pre>
or run the commands in <b>scripts/gview_load.py</b> by hand in the Django shell.
</p>
</body></html>

dj4e/dj4e-samples-main/gview/templates/gview/wacky.html
<h1>List of {{ crazy_thing }}s</h1>
<p>
{% if horse_list %}
<ul>
  {% for xyz in horse_list %}
    <li>
      <a href="{% url 'gview:horse' xyz.id %}">{{ xyz.name }}</a>
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no {{ crazy_thing }}s in the database.</p>
{% endif %}
</p>